---
###############################################################################
# Define defaults and template anchors
###############################################################################
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DOCKER_DRIVER: overlay2
  CLICKABLE_VERSION: "7"
  UT_VERSION: "16.04"

.node_anchors:
  click_path: &click_path
  - 'build/${ARCH_TRIPLET}/app/*.click'

  amd64: &amd64
    variables:
      ARCH: "amd64"
      ARCH_TRIPLET: "x86_64-linux-gnu"
  arm64: &arm64
    variables:
      ARCH: "arm64"
      ARCH_TRIPLET: "aarch64-linux-gnu"
  armhf: &armhf
    variables:
      ARCH: "armhf"
      ARCH_TRIPLET: "arm-linux-gnueabihf"

default:
  image: "clickable/ci-$UT_VERSION-$ARCH:$CLICKABLE_VERSION"

###############################################################################
# Define stages
###############################################################################
stages:
- clean
- build

# clean stage
.clean:
  stage: clean
  script:
  - clickable clean

###############################################################################
# `build` stage: build clicks for all architectures
###############################################################################
.build:
  stage: build
  script:
  - clickable build
  artifacts:
    paths: *click_path
    expire_in: 1 week

build_amd64:
  <<: *amd64
  extends: .build

build_arm64:
  <<: *arm64
  extends: .build

build_armhf:
  <<: *armhf
  extends: .build
